spring.application.name=demo-ticktick-mock

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://taskdb_flkm_user:MehNr8Hupcp2wYsnnFZm5isf4LW8dc8s@dpg-davkg25g1s2s73as5olg-a/taskdb_flkm
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true